<!DOCTYPE html>
<html>
    <head>
        <meta chatset="UTF-8" >
        <title>SYSTEM KINOWY - BILETY</title>
        <link rel="stylesheet" href="style1.css">
        <meta name="theme-color" content="#808080">
    </head>
    <body>
    <nav>
        <h2>NAWIGACJA</h2>
        <a href="index.php" target=""> STRONA GLOWNA</a>
    </nav>
        <header>
            <h2>TWOJE BILETY</h2>
        </header>
        
    </body>
</html>